services:
  mariadb:
    image: mariadb:11.6-ubi
    container_name: gai-scraper-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - gai_scraper_mariadb_data:/var/lib/mysql

volumes:
  gai_scraper_mariadb_data: